title: LJ Valencia
description: My personal page for all things Economics and not.
show_downloads: true

baseurl: # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://lj-valencia.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: LJ Valencia
image: /thumbnail-jumbo.png
twitter:
  username: SoyLeroy
  
plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['projects', 'about']
# header_page_refs: ['projects', 'about', 'contact']; use this to add contact portion.
