title: LJ Valencia
description: Hello there! Welcome to my personal page! 
show_downloads: true

url: "https://lj-valencia.github.io" # change this to the base hostname & protocol for your site
baseurl: # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.

google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

collections:
  projects:
    output: true
     
# social
author: LJ Valencia
# image: /thumbnail-jumbo.png
image: /lj-valencia-site.JPG
twitter:
  username: SoyLeroy
linkedin_username: lj-valencia

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['projects', 'about']
# header_page_refs: ['projects', 'about', 'contact']; use this to add contact portion.
